name: skip_app
description: A line-skipping food ordering app for food courts

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. Remove this before publishing.
publish_to: 'none'

# The app's version and build number
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dev_dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Location Services
  geolocator: ^10.1.0

  # Network Requests
  http: ^1.1.2
  dio: ^5.4.0

  # Firebase Dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

  # Payment Integration
  razorpay_flutter: ^1.3.5

  # Notifications

  # UI Enhancements
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9

  # Routing
  go_router: ^13.0.0

  # State Management Helpers
  flutter_riverpod: ^2.4.9

  # Utility
  intl: ^0.19.0
  uuid: ^4.2.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.13
  qr_flutter: ^4.0.0
  google_fonts: ^5.0.0
  overlay_support: ^2.1.0
  animated_text_kit: ^4.2.0
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.1
  image_picker: ^1.1.2
  convex_bottom_bar: ^3.2.0
  intl: ^0.19.0
  permission_handler: ^11.3.1
  lottie: ^3.1.2
  web: ^1.0.0
  cached_network_image: ^3.4.1
  provider: ^6.1.2
  lucide_icons: ^0.257.0

  # Mock Testing
  mockito: ^5.4.3

  # Code Generation
  build_runner: ^2.4.7

flutter:
  # Enable Material Design
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"  # Background color
  image: "lib/assets/images/splash.png"  # Your splash screen image
  android: true
  ios: true
  web: false
  # Assets configuration
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

  # Font configuration
